FROM node:14
WORKDIR /app
# Copy package.json and package-lock.json (if available)
COPY package*.json ./
RUN npm install
# Copy the rest of the frontend directory
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]