version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - report_server
      - news_pipeline_server
    environment:
      - REPORT_SERVER_URL=http://report_server:8001
      - NEWS_PIPELINE_SERVER_URL=http://news_pipeline_server:8002
      - MONGO_URI=mongodb://mongodb:27017 
    env_file:
      - .env

  report_server:
    build:
      context: .
      dockerfile: em_research_agentic/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    env_file:
      - .env
  
  news_pipeline_server:
    build:
      context: .
      dockerfile: em_news_analysis/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./em_news_analysis/config:/app/config

  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    

volumes:
  mongodb_data: