services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - report_server
      - news_pipeline_server
      - redis
      - research_chat
      - data_chat
    environment:
      - REPORT_SERVER_URL=http://report_server:8001
      - NEWS_PIPELINE_SERVER_URL=http://news_pipeline_server:8002
      - REPORT_CHAT_SERVER_URL=http://research_chat:8003
      - DATA_CHAT_SERVER_URL=http://data_chat:8004
      - MONGO_URI=mongodb://mongodb:27017 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env

  report_server:
    build:
      context: ./em_research_agentic
      dockerfile: Dockerfile
    image: ghcr.io/rraffay/nuntium_em:report-server-latest
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    env_file:
      - .env
  
  news_pipeline_server:
    build:
      context: ./em_news_analysis
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=config/em-news-gdelt.json
    volumes:
      - ./em_news_analysis/config:/app/config

  mongodb:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["mongod", "--bind_ip", "localhost,mongodb"]

  research_chat:
    build:
      context: ./em_research_chat
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - mongodb
    
  data_chat:
    build:
      context: ./em_data_chat
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - mongodb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: