services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/rraffay/nuntium_em:frontend-latest
    environment:
      - REACT_APP_API_BASE_URL=${FRONTEND_URL}/api
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    image: ghcr.io/rraffay/nuntium_em:backend-latest
    depends_on:
      - mongodb
      - report_server
      - news_pipeline_server
      - redis
      - research_chat
    environment:
      - REPORT_SERVER_URL=http://report_server:8001
      - NEWS_PIPELINE_SERVER_URL=http://news_pipeline_server:8002
      - REPORT_CHAT_SERVER_URL=http://research_chat:8003
      - MONGO_URI=mongodb://mongodb:27017 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ORIGINS=${CORS_ORIGINS}
      - FRONTEND_URL=${FRONTEND_URL}
    env_file:
      - .env

  report_server:
    build:
      context: ./em_research_agentic
      dockerfile: Dockerfile
    image: ghcr.io/rraffay/nuntium_em:report-server-latest
    depends_on:
      - mongodb
    env_file:
      - .env
  
  news_pipeline_server:
    build:
      context: ./em_news_analysis
      dockerfile: Dockerfile
    image: ghcr.io/rraffay/nuntium_em:news-pipeline-latest
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=config/em-news-gdelt.json
    volumes:
      - ./em_news_analysis/config:/app/config

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    
  research_chat:
    build:
      context: ./em_research_chat
      dockerfile: Dockerfile
    image: ghcr.io/rraffay/nuntium_em:research-chat-latest
    depends_on:
      - mongodb
    env_file:
      - .env

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  nginx:
       image: nginx:latest
       ports:
         - "80:80"
       volumes:
         - ./nginx.conf:/etc/nginx/conf.d/default.conf
         - ./certbot/www:/var/www/certbot
       depends_on:
         - frontend
         - backend
         - report_server
         - news_pipeline_server
         - research_chat

volumes:
  mongodb_data:
  redis_data: