services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      report_server:
        condition: service_started
      news_pipeline_server:
        condition: service_started
      research_chat:
        condition: service_started
      data_chat:
        condition: service_started
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 20s
      retries: 3

  report_server:
    build:
      context: ./em_research_agentic
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 900s
      timeout: 450s
      retries: 2

  news_pipeline_server:
    build:
      context: ./em_news_analysis
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=config/em-news-gdelt.json
    volumes:
      - ./em_news_analysis/config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 360s
      timeout: 180s
      retries: 2

  mongodb:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /mnt/volume_nyc1_01/mongodb:/data/db
    command: ["mongod", "--bind_ip", "localhost,mongodb"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  research_chat:
    build:
      context: ./em_research_chat
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 900s
      timeout: 450s
      retries: 2

  redis:
    image: redis:latest
    volumes:
      - /mnt/volume_nyc1_01/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
      - report_server
      - news_pipeline_server
      - research_chat
      - data_chat  

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ranaraffay@gmail.com -d nuntiumai.xyz -d www.nuntiumai.xyz --agree-tos --no-eff-email

  data_chat:
    build:
      context: ./em_data_chat
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 900s
      timeout: 450s
      retries: 2

volumes:
  certbot_data: