import os
import logging
from em_news_analysis import DevelopmentConfig, GDELTNewsPipeline
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'config/em-news-gdelt.json'


def main():
    config = DevelopmentConfig()
    pipeline = GDELTNewsPipeline(config)

    try:
        results = pipeline.run_pipeline(
            input_sentence="Event about Mexico. Specifically, focusing on MacroEconomics .",
            country="MX",  # FIPS 10-4 country code for Mexico,
            user_id='66e37d739f82246a180b4dff',
            hours=2,
            article_summarizer_objective="Analyze for someone interested in events about Mexico. ",
            cluster_summarizer_objective="Analyze for someone interested in events about Mexico. Specifically, focusing on MacroEconomics .",
            process_all=False,
            sample_size=1500,
            max_workers_embeddings=5,
            max_workers_summaries=3,
            export_to_local=True
        )
        if results:
            print("Pipeline results:")
            for i, summary in enumerate(results, 1):
                print(f"Cluster {i} summary: {summary}")
        else:
            print("No results generated by the pipeline.")
    except Exception as e:
        logger.error(
            f"An error occurred while running the pipeline: {str(e)}", exc_info=True)


if __name__ == "__main__":
    main()
