name: Publish Docker images

on:
  push:
    branches: [ "prod-ready" ]
  pull_request:
    branches: [ "prod-ready" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:${{ github.sha }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:${{ github.sha }}

      - name: Build and push Report Server image
        uses: docker/build-push-action@v4
        with:
          context: ./em_research_agentic
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/report_server:${{ github.sha }}

      - name: Build and push News Pipeline Server image
        uses: docker/build-push-action@v4
        with:
          context: ./em_news_analysis
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/news_pipeline_server:${{ github.sha }}

      - name: Build and push Research Chat image
        uses: docker/build-push-action@v4
        with:
          context: ./em_research_chat
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/research_chat:${{ github.sha }}